name: Deploy CV Analyzer to Azure

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: your-docker-registry.azurecr.io
        username: ${{ secrets.AZURE_USERNAME }}
        password: ${{ secrets.AZURE_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t your-docker-registry.azurecr.io/cv-analyzer-app:${{ github.sha }} .

    - name: Push Docker image to Azure Container Registry
      run: |
        docker push your-docker-registry.azurecr.io/cv-analyzer-app:${{ github.sha }}

    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: cv-analyzer-app
        slot-name: production
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: your-docker-registry.azurecr.io/cv-analyzer-app:${{ github.sha }}
